name: Deploy Production

run-name: ${{ github.actor }} is deploying Gamebot to production

on:
  # Run scheduled weekly restarts at 5:30PM Saturday UTC (10:30 PDT)
  schedule:
    - cron: "30 17 * * SAT"
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: master
        required: false

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-staging.yml
    with:
      branch: master
    secrets: inherit
  deploy:
    needs: deploy-staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      log_level: info
      branch: master
    secrets: inherit